version: "3.7"

services:
  web:
    image: webdevops/php-apache:8.0-alpine
    container_name: Apache-PHP
    ports:
      - "4500:80"
    volumes:
      - ./src:/app
    links:
      - database

  database:
    image: mysql:8.0
    container_name: MySQL
    restart: always
    ports:
      - "8083:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contatoseguro
      MYSQL_USER: userBD
      MYSQL_PASSWORD: 12345
    volumes:
      - "/var/lib/mysqlDocker"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: phpMyAdmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
    ports:
      - "8080:80"
    links:
      - database

volumes:
  data: